### ISSUE TITLE
HOTEL_000C Prepare basic data set

### ISSUE THREAD

**Issue by sledgy-7** [sw20-tug/SWT-Morning-1#19]
Prepare basic data set to ensure data is present for landing page implementation.

**Comment by maei95** [comment]
Dataset:

class Hotel
{
  name              (string)

  description       (string) 

  thumbnail picture (image)

  list of Pictures  (list images)

  stars from 1 to 5 (int)

  List of Ratings   (list objects)

  Location          (string)
   
  Price             (int)

  List of activities (list of objects)
} 

class Rating
{
  Rating from 1-10  (int)
  comment           (string)
  User              (object)
}

class User
{
  name      (string)
  email     (string)
  password  (byte array)
  seed      (byte array)
}

class Activities
{
  type        (string)
  description (string)
}

**Comment by sledgy-7** [comment]
Define test cases
